# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4efcc5e82f675cf97eda09551a3d21e258b18c007714aa33abf7944db207b33f66f376708e83dcfdcf024bc6671fc67a42e4795e9e3583946b32bd0b23f2588

test:
  secret_key_base: 5dd38a17662a754e1578068f7cc89f2ae7e28e564f754ff37f247d612959a84ef6a567c917b981613a2efbdf5eb3be92524f3f391e4965635a1562d1ef55d769

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
